spring:
  application:
    name: todo

  datasource:
    url: jdbc:postgresql://localhost:5434/todo
    driver-class-name: org.postgresql.Driver
    username: todo_dev
    password: todo_dev12


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8080
